### ISSUE TITLE
Feature: Use Postgres LTREE for groups hierarchy

### ISSUE THREAD

**Issue by arvindh123** [Mainflux/mainflux-lite#2214] opened 2024-05-03 10:41 UTC
### Is your feature request related to a problem? Please describe.

Reference: https://github.com/absmach/magistrala/issues/1980

## Implmentation
- [x] Create Extension LTREE in postgres
- [x] Add a column with name `path` and type as `LTREE`
- [ ] While inserting new row
       If the inserting new row have no parent . `path` column should have value of `id`
       If the inserting new row have parent, Get the path column should have `parent path` + `.`+ `id`
- [ ] Retrieve [Ancestors / Parents](https://github.com/absmach/magistrala/issues/1980#get-parents) and [Descendants / Children](https://github.com/absmach/magistrala/issues/1980#get-children) by using the below given in #1980

### Indicate the importance of this feature to you.

Should-have

**Comment by dborovcanin** [comment] 2024-10-08 07:55
This is in progress in https://github.com/absmach/magistrala/pull/2409.

**Comment by dborovcanin** [comment] 2024-10-23 07:51
I am closing as a duplicate of #1980.

**Closed as completed by dborovcanin** 2024-10-23 07:51 UTC
