### ISSUE TITLE
Fix Nats Failed to Unmarshal MQTT Data

### ISSUE THREAD

**Issue by rodneyosodo** [Mainflux/mainflux-lite#2021] opened 2023-10-25 06:48 UTC
Fix the following error

```bash
mainflux-mqtt             | {"level":"warn","message":"Failed to unmarshal received message: proto: cannot parse invalid wire-format data","ts":"2023-10-25T06:44:27.506603048Z"}
```

A possible reason behind it is the failure to decode Payload data to MF Message

**Comment by nintran52** [comment] 2024-02-17 14:14
When I debug I saw, that NATS resend a raw message from the MQTT client (not message.proto)

**Comment by nintran52** [comment] 2024-02-17 15:37
NATS Subscribe received 2 messages, one from Mqtt (with raw format from clients) and another from NATS publisher (after converting to messaging struct)
- First message can not Unmarshal from proto and re-receive after 30s
- The messages from the retry caused the system to stall

**Comment by drasko** [comment] 2024-02-17 15:40
@dborovcanin and @arvindh123  please take a look at this issue

**Comment by nintran52** [comment] 2024-02-19 09:29
NATS clients also receive messages from MQTT, so to fix this issue I think we need to separate MQTT Broker and NATS Message into two (don't use the same NATS)
cc: @dborovcanin, @arvindh123

**Comment by dborovcanin** [comment] 2024-02-19 09:49
Hello, @nintran52,
> To fix this issue I think we need to separate MQTT Broker and NATS Message

This is true. However, we have separated it in v0.14.0 by reverting the VerneMQ to be the default MQTT broker. There are other reasons for that, such as that NATS does not support the full range of MQTT 3.1 features and it would limit our MQTT support, as well as support for protocols that are built on top of MQTT (such as [Sparkplug](https://sparkplug.eclipse.org/specification/)).

**Comment by dborovcanin** [comment] 2024-05-15 10:55
Closing the issue since it was caused by using the same instance of NATS for Proto messages and MQTT messages. We opted for using VerneMQ due to better MQTT support.

**Closed as completed by dborovcanin** 2024-05-15 10:55 UTC
Labels: bug
